[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "apscheduler>=3.11.0",
    "feedparser>=6.0.11",
    "flask>=3.1.0",
    "googletrans>=4.0.2",
    "telegram>=0.0.1",
]
